import * as Dialog from "@radix-ui/react-dialog";
import { Download, Eye, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { emptyObservationHistoryFilters, exportObservationHistory, getObservationHistory, type ObservationHistoryFilters, type ObservationHistoryItem } from "../../api/scientificMembers";
import { getAmirObservation, getTeacherObservation, type AmirObservationDetail, type TeacherObservationDetail } from "../../api/observations";
import { getFinalResultLabel, getObservationTypeLabel, formatAmirCompetency, formatTeacherCompetency } from "../../lib/observationLabels";
import { getJobTitleLabel } from "../../lib/employeeLabels";
import type { ScientificMember } from "../../types/api";
import { Button } from "../ui/button";
import { EmptyState, ErrorState, LoadingState } from "../shared/states";

interface Props { member: ScientificMember | null; onOpenChange: (open: boolean) => void; }
type Detail = { item: ObservationHistoryItem; data: TeacherObservationDetail & AmirObservationDetail };

export function ObservationHistoryDialog({ member, onOpenChange }: Props) {
  const [filters, setFilters] = useState<ObservationHistoryFilters>({ ...emptyObservationHistoryFilters }); const [items, setItems] = useState<ObservationHistoryItem[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [exporting, setExporting] = useState(false); const [detail, setDetail] = useState<Detail | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const load = useCallback(async () => { if (!member) return; setLoading(true); setError(""); try { const response = await getObservationHistory(member.id, { ...filters, page, page_size: 20 }); setItems(response.items); setTotal(response.total); } catch { setError("دریافت سابقهٔ مشاهدات با مشکل روبه‌رو شد."); } finally { setLoading(false); } }, [filters, member, page]);
  useEffect(() => { if (member) { setFilters({ ...emptyObservationHistoryFilters }); setPage(1); } }, [member]);
  useEffect(() => { if (member) void load(); }, [load, member]);
  const update = (key: keyof ObservationHistoryFilters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const openDetail = async (item: ObservationHistoryItem) => { setDetailLoading(true); try { const data = item.observation_type === "teacher" ? await getTeacherObservation(item.observed_employee_id, item.observation_id) : await getAmirObservation(item.observed_employee_id, item.observation_id); setDetail({ item, data: data as TeacherObservationDetail & AmirObservationDetail }); } catch { setError("دریافت جزئیات مشاهده با مشکل روبه‌رو شد."); } finally { setDetailLoading(false); } };
  const download = async () => { if (!member) return; setExporting(true); try { await exportObservationHistory(member.id); } catch { setError("صدور فایل اکسل مشاهدات با مشکل روبه‌رو شد."); } finally { setExporting(false); } };
  const pages = Math.max(1, Math.ceil(total / 20));
  return <><Dialog.Root open={Boolean(member)} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-slate-950/30" /><Dialog.Content className="fixed inset-x-3 top-3 bottom-3 z-50 mx-auto flex max-w-6xl flex-col rounded-xl border border-line bg-white shadow-panel sm:inset-y-6"><div className="flex items-start justify-between border-b border-line px-5 py-4"><div><Dialog.Title className="font-bold text-ink">سوابق مشاهدات</Dialog.Title><Dialog.Description className="mt-1 text-sm text-muted">{member ? `${member.name} ${member.surname}` : ""}</Dialog.Description></div><div className="flex items-center gap-2"><Button className="h-9" disabled={exporting} onClick={() => void download()}><Download size={16} />دانلود اکسل</Button><Dialog.Close asChild><button className="p-1 text-muted" aria-label="بستن"><X size={19} /></button></Dialog.Close></div></div><div className="min-h-0 flex-1 overflow-y-auto p-5"><HistoryFilters filters={filters} onChange={update} onClear={() => { setFilters({ ...emptyObservationHistoryFilters }); setPage(1); }} />{loading ? <div className="mt-4"><LoadingState title="در حال دریافت مشاهدات" description="سابقهٔ مشاهدات در حال بارگذاری است." /></div> : error ? <div className="mt-4"><ErrorState title="خطا در دریافت اطلاعات" description={error} /></div> : items.length === 0 ? <div className="mt-4"><EmptyState title="مشاهده‌ای یافت نشد" description="برای این عضو علمی سابقهٔ فعال ثبت نشده است." /></div> : <><HistoryTable items={items} onDetail={(item) => void openDetail(item)} detailLoading={detailLoading} /><div className="mt-4 flex items-center justify-between text-sm"><span className="text-muted">{total.toLocaleString("fa-AF")} مشاهده</span><div className="flex gap-2"><Button className="h-9" disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>قبلی</Button><span className="py-2 text-muted">{page.toLocaleString("fa-AF")} از {pages.toLocaleString("fa-AF")}</span><Button className="h-9" disabled={page >= pages} onClick={() => setPage((current) => current + 1)}>بعدی</Button></div></div></>}</div></Dialog.Content></Dialog.Portal></Dialog.Root><ObservationDetailDialog detail={detail} onOpenChange={(open) => { if (!open) setDetail(null); }} /></>;
}

function HistoryFilters({ filters, onChange, onClear }: { filters: ObservationHistoryFilters; onChange: (key: keyof ObservationHistoryFilters, value: string) => void; onClear: () => void }) { return <div className="grid gap-2 rounded-xl border border-line bg-slate-50/80 p-3 sm:grid-cols-2 lg:grid-cols-6"><select className="input" value={filters.observation_type} onChange={(event) => onChange("observation_type", event.target.value)}><option value="">نوع مشاهده</option><option value="teacher">مشاهده معلم</option><option value="amir_senior_teacher">مشاهده آمر / سرمعلم</option></select><input type="date" className="input" value={filters.date_from} onChange={(event) => onChange("date_from", event.target.value)} /><input type="date" className="input" value={filters.date_to} onChange={(event) => onChange("date_to", event.target.value)} /><input className="input" inputMode="numeric" placeholder="شماره کارمند" value={filters.employee_id} onChange={(event) => onChange("employee_id", event.target.value)} /><select className="input" value={filters.final_result_code} onChange={(event) => onChange("final_result_code", event.target.value)}><option value="">نتیجه نهایی</option><option value="needs_improvement">نیازمند بهبود</option><option value="has_capability">دارای قابلیت</option><option value="basic_capability">قابلیت ابتدایی</option><option value="applied_capability">قابلیت بکارگیری</option><option value="mastery">تسلط بر قابلیت / مسلط بر قابلیت</option></select><Button className="h-10" onClick={onClear}>پاک‌کردن</Button></div>; }
function HistoryTable({ items, onDetail, detailLoading }: { items: ObservationHistoryItem[]; onDetail: (item: ObservationHistoryItem) => void; detailLoading: boolean }) { return <div className="mt-4 overflow-x-auto rounded-xl border border-line"><table className="min-w-full divide-y divide-line text-right text-sm"><thead className="bg-slate-50 text-muted"><tr>{["تاریخ مشاهده", "کارمند مشاهده‌شده", "ولد", "عنوان وظیفه", "نوع مشاهده", "مضمون", "مجموع نمره", "نتیجه نهایی", "عملیات"].map((title) => <th key={title} className="whitespace-nowrap px-3 py-3 font-semibold">{title}</th>)}</tr></thead><tbody className="divide-y divide-line">{items.map((item) => <tr key={`${item.observation_type}-${item.observation_id}`}><td className="px-3 py-3">{item.observation_date}</td><td className="px-3 py-3 font-medium">{item.observed_employee_name}</td><td className="px-3 py-3">{item.observed_employee_father_name}</td><td className="px-3 py-3">{getJobTitleLabel(item.observed_employee_job_title_code)}</td><td className="px-3 py-3">{getObservationTypeLabel(item.observation_type)}</td><td className="px-3 py-3">{item.subject}</td><td className="px-3 py-3">{item.total_score}</td><td className="px-3 py-3">{getFinalResultLabel(item.final_result_code, item.observation_type)}</td><td className="px-3 py-3"><Button className="h-8 px-2" disabled={detailLoading} onClick={() => onDetail(item)}><Eye size={15} />جزئیات</Button></td></tr>)}</tbody></table></div>; }
function ObservationDetailDialog({ detail, onOpenChange }: { detail: Detail | null; onOpenChange: (open: boolean) => void }) { const isTeacher = detail?.item.observation_type === "teacher"; const data = detail?.data; const scores = data ? isTeacher ? [["دانش مضمونی", data.subject_knowledge_score], ["پلان درسی", data.lesson_plan_score], ["مدیریت صنف", data.classroom_management_score], ["ارزیابی", data.assessment_score], ["آموزش‌های مسلکی", data.professional_learning_score], ["ارتباط با اجتماع", data.community_engagement_score]] : [["مسوولیت پذیری", data.responsibility_score], ["رهبری مسلکی", data.professional_leadership_score], ["روابط با جامعه", data.community_relations_score], ["انکشاف مسلکی", data.professional_development_score]] : []; return <Dialog.Root open={Boolean(detail)} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[60] bg-slate-950/30" /><Dialog.Content className="fixed inset-x-3 top-1/2 z-[60] mx-auto max-h-[calc(100vh-2rem)] max-w-3xl -translate-y-1/2 overflow-y-auto rounded-xl border border-line bg-white shadow-panel sm:inset-x-6">{detail && data ? <><div className="flex justify-between border-b border-line px-5 py-4"><Dialog.Title className="font-bold">جزئیات مشاهده</Dialog.Title><Dialog.Close asChild><button className="p-1 text-muted" aria-label="بستن"><X size={19} /></button></Dialog.Close></div><div className="space-y-5 p-5"><dl className="grid gap-3 sm:grid-cols-2"><Info label="کارمند مشاهده‌شده" value={`${detail.item.observed_employee_name} — ولد ${detail.item.observed_employee_father_name}`} /><Info label="مشاهده‌کننده" value={`${data.observer.name} ${data.observer.surname}`} /><Info label="تاریخ مشاهده" value={data.observation_date} /><Info label="صنف مشاهده شده" value={data.observed_class} /><Info label="مضمون" value={data.subject} /><Info label="مجموع نمره" value={data.total_score} /><Info label="نتیجه نهایی" value={getFinalResultLabel(data.final_result_code, detail.item.observation_type)} /></dl><section><h2 className="mb-3 text-sm font-bold">قابلیت‌ها</h2><div className="grid gap-2 sm:grid-cols-2">{scores.map(([label, score]) => <div key={label as string} className="rounded-lg bg-slate-50 px-3 py-2 text-sm"><span className="text-muted">{label as string}</span><p className="mt-1 text-ink">{isTeacher ? formatTeacherCompetency(score as number) : formatAmirCompetency(score as number)}</p></div>)}</div></section><dl className="grid gap-3 sm:grid-cols-3"><Info label="نکات قوت" value={data.strengths || "—"} /><Info label="نکات قابل اصلاح" value={data.improvements || "—"} /><Info label="ملاحظات" value={data.notes || "—"} /></dl></div></> : null}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
function Info({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg bg-slate-50 px-3 py-2"><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm text-ink">{value}</dd></div>; }
