import * as Dialog from "@radix-ui/react-dialog";
import { Search, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { createScientificMember, updateScientificMember, type ScientificMemberPayload } from "../../api/scientificMembers";
import { getDepartmentLabel } from "../../lib/departmentLabels";
import type { Department, ScientificMember } from "../../types/api";
import { Button } from "../ui/button";

interface Props { open: boolean; onOpenChange: (open: boolean) => void; member?: ScientificMember; departments: Department[]; onSaved: (message: string) => void; }
const blank = { name: "", surname: "", father_name: "", phone_number: "", academic_rank: "", department_id: "", notes: "" };

export function ScientificMemberFormDialog({ open, onOpenChange, member, departments, onSaved }: Props) {
  const [values, setValues] = useState(blank); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setValues(member ? { name: member.name, surname: member.surname, father_name: member.father_name, phone_number: member.phone_number, academic_rank: member.academic_rank, department_id: String(member.department_id), notes: member.notes ?? "" } : blank); setSearch(""); setError(""); } }, [member, open]);
  const visibleDepartments = useMemo(() => departments.filter((department) => getDepartmentLabel(department.code, department.display_name).includes(search.trim())), [departments, search]);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!values.name.trim() || !values.surname.trim() || !values.father_name.trim() || !values.phone_number.trim() || !values.academic_rank.trim() || !values.department_id) { setError("تمام فیلدهای الزامی را تکمیل کنید."); return; } setSaving(true); setError(""); const payload: ScientificMemberPayload = { ...values, name: values.name.trim(), surname: values.surname.trim(), father_name: values.father_name.trim(), phone_number: values.phone_number.trim(), academic_rank: values.academic_rank.trim(), department_id: Number(values.department_id), notes: values.notes.trim() || null }; try { if (member) { await updateScientificMember(member.id, payload); onSaved("اطلاعات عضو علمی به‌روزرسانی شد."); } else { await createScientificMember(payload); onSaved("عضو علمی جدید با موفقیت ثبت شد."); } onOpenChange(false); } catch { setError("ثبت اطلاعات با مشکل روبه‌رو شد. لطفاً دوباره کوشش کنید."); } finally { setSaving(false); } };
  const set = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: value }));
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-slate-950/30" /><Dialog.Content className="fixed inset-x-3 top-1/2 z-50 mx-auto max-h-[calc(100vh-2rem)] max-w-2xl -translate-y-1/2 overflow-y-auto rounded-xl border border-line bg-white shadow-panel sm:inset-x-6"><div className="flex items-start justify-between border-b border-line px-5 py-4"><div><Dialog.Title className="font-bold text-ink">{member ? "ویرایش عضو علمی" : "افزودن عضو علمی"}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-muted">مشخصات و دیپارتمنت مربوطه را وارد کنید.</Dialog.Description></div><Dialog.Close asChild><button className="p-1 text-muted" aria-label="بستن"><X size={19} /></button></Dialog.Close></div><form noValidate onSubmit={submit} className="p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="اسم"><input className="input" value={values.name} onChange={(event) => set("name", event.target.value)} /></Field><Field label="تخلص"><input className="input" value={values.surname} onChange={(event) => set("surname", event.target.value)} /></Field><Field label="ولد"><input className="input" value={values.father_name} onChange={(event) => set("father_name", event.target.value)} /></Field><Field label="شماره تماس"><input dir="ltr" className="input" value={values.phone_number} onChange={(event) => set("phone_number", event.target.value)} /></Field><Field label="رتبه علمی"><input className="input" value={values.academic_rank} onChange={(event) => set("academic_rank", event.target.value)} /></Field><Field label="دیپارتمنت"><div className="space-y-2"><div className="relative"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-muted" size={15} /><input className="input pr-9" placeholder="جستجوی دیپارتمنت" value={search} onChange={(event) => setSearch(event.target.value)} /></div><select className="input" value={values.department_id} onChange={(event) => set("department_id", event.target.value)}><option value="">انتخاب دیپارتمنت</option>{visibleDepartments.map((department) => <option key={department.id} value={department.id}>{getDepartmentLabel(department.code, department.display_name)}</option>)}</select></div></Field></div><div className="mt-4"><Field label="ملاحظات"><textarea className="textarea" value={values.notes} onChange={(event) => set("notes", event.target.value)} /></Field></div>{error ? <p role="alert" className="mt-4 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-800">{error}</p> : null}<div className="mt-5 flex justify-end gap-2"><Dialog.Close asChild><Button disabled={saving}>انصراف</Button></Dialog.Close><Button type="submit" disabled={saving} variant="primary">{saving ? "در حال ثبت" : "ثبت اطلاعات"}</Button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-sm font-medium text-ink">{label}</span>{children}</label>; }
