import { useCallback, useEffect, useState } from "react";
import { ClipboardList, Download, Eye, Pencil, Plus, Trash2 } from "lucide-react";
import { getDepartments } from "../api/departments";
import { deleteScientificMember, emptyScientificMemberFilters, exportScientificMembers, getScientificMembers, type ScientificMemberFilters } from "../api/scientificMembers";
import { ObservationHistoryDialog } from "../components/scientific-members/ObservationHistoryDialog";
import { ScientificMemberDetailsDialog } from "../components/scientific-members/ScientificMemberDetailsDialog";
import { ScientificMemberFormDialog } from "../components/scientific-members/ScientificMemberFormDialog";
import { ConfirmDialog } from "../components/shared/ConfirmDialog";
import { EmptyState, ErrorState, LoadingState } from "../components/shared/states";
import { PageHeader } from "../components/shared/PageHeader";
import { Button } from "../components/ui/button";
import { useToast } from "../components/ui/toast";
import { getDepartmentLabel } from "../lib/departmentLabels";
import type { Department, PaginatedResponse, ScientificMember } from "../types/api";

export function ScientificMembersPage() {
  const { showToast } = useToast(); const [filters, setFilters] = useState<ScientificMemberFilters>({ ...emptyScientificMemberFilters }); const [members, setMembers] = useState<PaginatedResponse<ScientificMember> | null>(null); const [departments, setDepartments] = useState<Department[]>([]); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [exporting, setExporting] = useState(false); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<ScientificMember | undefined>(); const [details, setDetails] = useState<ScientificMember | null>(null); const [history, setHistory] = useState<ScientificMember | null>(null); const [reload, setReload] = useState(0);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await getScientificMembers({ ...filters, page, page_size: 20, sort_by: "id", sort_order: "asc" }); setMembers(result); if (!result.items.length && result.total && page > 1) setPage((current) => current - 1); } catch { setError("دریافت اعضای علمی با مشکل روبه‌رو شد."); } finally { setLoading(false); } }, [filters, page, reload]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { getDepartments().then(setDepartments).catch(() => showToast("دریافت دیپارتمنت‌ها با مشکل روبه‌رو شد.", "error")); }, [showToast]);
  const update = (key: keyof ScientificMemberFilters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const afterSave = (message: string) => { showToast(message); setPage(1); setReload((current) => current + 1); };
  const remove = async (member: ScientificMember) => { try { await deleteScientificMember(member.id); showToast("عضو علمی از فهرست فعال حذف شد."); setReload((current) => current + 1); } catch { showToast("حذف عضو علمی با مشکل روبه‌رو شد.", "error"); } };
  const exportFile = async () => { setExporting(true); try { await exportScientificMembers(filters); showToast("فایل اکسل با فیلترهای فعلی آماده دانلود شد."); } catch { showToast("صدور فایل اکسل با مشکل روبه‌رو شد.", "error"); } finally { setExporting(false); } };
  const items = members?.items ?? []; const pages = Math.max(1, Math.ceil((members?.total ?? 0) / 20));
  return <div className="space-y-6"><PageHeader title="اعضای علمی" description="مدیریت اعضای علمی و مشاهده سوابق مشاهدات" actions={<><Button disabled={exporting} onClick={() => void exportFile()}><Download size={17} />{exporting ? "در حال آماده‌سازی" : "دانلود اکسل"}</Button><Button variant="primary" onClick={() => { setEditing(undefined); setFormOpen(true); }}><Plus size={18} />افزودن عضو علمی</Button></>} /><Filters filters={filters} departments={departments} onChange={update} onClear={() => { setFilters({ ...emptyScientificMemberFilters }); setPage(1); }} /><p className="text-sm text-muted">{members ? `${members.total.toLocaleString("fa-AF")} عضو علمی یافت شد` : ""}</p>{loading ? <LoadingState title="در حال دریافت اعضای علمی" description="فهرست اعضای علمی در حال بارگذاری است." /> : error ? <div className="space-y-3"><ErrorState title="خطا در دریافت اطلاعات" description={error} /><Button onClick={() => void load()}>کوشش دوباره</Button></div> : items.length === 0 ? <EmptyState title="عضو علمی یافت نشد" description="فیلترها را تغییر دهید یا عضو علمی جدیدی ثبت کنید." /> : <><MembersTable items={items} onDetails={setDetails} onEdit={(member) => { setEditing(member); setFormOpen(true); }} onHistory={setHistory} onDelete={(member) => void remove(member)} /><Pagination page={page} pages={pages} onPage={setPage} /></>}<ScientificMemberFormDialog open={formOpen} onOpenChange={setFormOpen} member={editing} departments={departments} onSaved={afterSave} /><ScientificMemberDetailsDialog member={details} onOpenChange={(open) => { if (!open) setDetails(null); }} /><ObservationHistoryDialog member={history} onOpenChange={(open) => { if (!open) setHistory(null); }} /></div>;
}

function Filters({ filters, departments, onChange, onClear }: { filters: ScientificMemberFilters; departments: Department[]; onChange: (key: keyof ScientificMemberFilters, value: string) => void; onClear: () => void }) { return <div className="grid gap-2 rounded-xl border border-line bg-slate-50/80 p-3 sm:grid-cols-2 lg:grid-cols-4"><input className="input" placeholder="جستجو" value={filters.search} onChange={(event) => onChange("search", event.target.value)} /><input className="input" placeholder="اسم" value={filters.name} onChange={(event) => onChange("name", event.target.value)} /><input className="input" placeholder="تخلص" value={filters.surname} onChange={(event) => onChange("surname", event.target.value)} /><input className="input" placeholder="ولد" value={filters.father_name} onChange={(event) => onChange("father_name", event.target.value)} /><input className="input" placeholder="رتبه علمی" value={filters.academic_rank} onChange={(event) => onChange("academic_rank", event.target.value)} /><select className="input" value={filters.department_id} onChange={(event) => onChange("department_id", event.target.value)}><option value="">دیپارتمنت</option>{departments.map((department) => <option key={department.id} value={department.id}>{getDepartmentLabel(department.code, department.display_name)}</option>)}</select><Button onClick={onClear}>پاک‌کردن</Button></div>; }
function MembersTable({ items, onDetails, onEdit, onHistory, onDelete }: { items: ScientificMember[]; onDetails: (member: ScientificMember) => void; onEdit: (member: ScientificMember) => void; onHistory: (member: ScientificMember) => void; onDelete: (member: ScientificMember) => void }) { return <div className="overflow-x-auto rounded-xl border border-line bg-white shadow-soft"><table className="min-w-full divide-y divide-line text-right text-sm"><thead className="bg-slate-50 text-muted"><tr>{["شماره", "اسم", "ولد", "رتبه علمی", "دیپارتمنت", "مشاهدات", "عملیات"].map((title) => <th key={title} className="whitespace-nowrap px-3 py-3 font-semibold">{title}</th>)}</tr></thead><tbody className="divide-y divide-line">{items.map((member) => <tr key={member.id} className="hover:bg-slate-50/80"><td className="px-3 py-3 text-muted">{member.id}</td><td className="px-3 py-3 font-medium text-ink">{member.name}</td><td className="px-3 py-3">{member.father_name}</td><td className="px-3 py-3">{member.academic_rank}</td><td className="px-3 py-3">{getDepartmentLabel(member.department.code, member.department.display_name)}</td><td className="px-3 py-3"><Button className="h-8 px-2" onClick={() => onHistory(member)}><ClipboardList size={15} />مشاهدات: {member.observation_count.toLocaleString("fa-AF")}</Button></td><td className="px-3 py-3"><div className="flex gap-1"><IconAction title="مشاهده جزئیات" onClick={() => onDetails(member)} icon={<Eye size={16} />} /><IconAction title="ویرایش" onClick={() => onEdit(member)} icon={<Pencil size={15} />} /><ConfirmDialog title="حذف عضو علمی" description={`آیا از حذف «${member.name}» اطمینان دارید؟`} confirmLabel="حذف عضو علمی" onConfirm={() => onDelete(member)} trigger={<IconAction title="حذف" icon={<Trash2 size={15} />} danger />} /></div></td></tr>)}</tbody></table></div>; }
function IconAction({ title, onClick, icon, danger = false }: { title: string; onClick?: () => void; icon: React.ReactNode; danger?: boolean }) { return <Button className={`h-8 w-8 px-0 ${danger ? "text-rose-700 hover:bg-rose-50" : ""}`} title={title} aria-label={title} onClick={onClick}>{icon}</Button>; }
function Pagination({ page, pages, onPage }: { page: number; pages: number; onPage: (page: number) => void }) { return <div className="mt-4 flex justify-end gap-2"><Button disabled={page <= 1} onClick={() => onPage(page - 1)}>قبلی</Button><span className="px-2 py-2 text-sm text-muted">{page.toLocaleString("fa-AF")} از {pages.toLocaleString("fa-AF")}</span><Button disabled={page >= pages} onClick={() => onPage(page + 1)}>بعدی</Button></div>; }
