import { LoaderCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { createEmployee, updateEmployee, type EmployeePayload } from "../../api/employees";
import { getDepartmentLabel } from "../../lib/departmentLabels";
import { educationLevelOptions, fieldMatchLabels, jobTitleLabels } from "../../lib/employeeLabels";
import type { Department, Employee } from "../../types/api";
import { AppDialog } from "../shared/AppDialog";
import { MultiSelect, SearchableSelect, type SelectOption } from "../shared/SearchableSelect";
import { Button } from "../ui/button";

type FormValues = Omit<EmployeePayload, "teaching_experience" | "grade_post" | "step"> & { teaching_experience: string; grade_post: string; step: string; };
type FieldName = keyof FormValues;
type FieldErrors = Partial<Record<FieldName, string>>;
const emptyValues: FormValues = { name: "", father_name: "", grandfather_name: "", school_workplace: "", city_district: "", phone_number: "", field_of_study: "", education_level: "", subjects_taught: "", job_title_code: "", teaching_experience: "", grade_post: "", step: "", successful_evaluation: "", field_match_code: "", department_ids: [], notes: "" };

function employeeToValues(employee?: Employee): FormValues { return employee ? { name: employee.name, father_name: employee.father_name, grandfather_name: employee.grandfather_name, school_workplace: employee.school_workplace, city_district: employee.city_district, phone_number: employee.phone_number, field_of_study: employee.field_of_study, education_level: employee.education_level, subjects_taught: employee.subjects_taught, job_title_code: employee.job_title_code, teaching_experience: String(employee.teaching_experience), grade_post: String(employee.grade_post), step: String(employee.step), successful_evaluation: employee.successful_evaluation, field_match_code: employee.field_match_code, department_ids: employee.departments.map((department) => department.id), notes: employee.notes ?? "" } : { ...emptyValues }; }
function validate(values: FormValues): FieldErrors { const errors: FieldErrors = {}; const required: FieldName[] = ["name", "father_name", "grandfather_name", "school_workplace", "city_district", "phone_number", "field_of_study", "education_level", "subjects_taught", "job_title_code", "successful_evaluation", "field_match_code"]; required.forEach((field) => { if (!String(values[field]).trim()) errors[field] = "این فیلد الزامی است."; }); (["teaching_experience", "grade_post", "step"] as const).forEach((field) => { const number = Number(values[field]); if (!Number.isInteger(number) || number < 0) errors[field] = "عدد صحیحِ صفر یا بیشتر وارد کنید."; }); return errors; }

interface Props { open: boolean; onOpenChange: (open: boolean) => void; departments: Department[]; employee?: Employee; onSaved: (message: string) => void; }

export function EmployeeFormDialog({ open, onOpenChange, departments, employee, onSaved }: Props) {
  const [values, setValues] = useState<FormValues>(() => employeeToValues(employee));
  const [errors, setErrors] = useState<FieldErrors>({});
  const [submitError, setSubmitError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  useEffect(() => { if (open) { setValues(employeeToValues(employee)); setErrors({}); setSubmitError(""); } }, [employee, open]);
  const setValue = <K extends FieldName>(field: K, value: FormValues[K]) => { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })); };
  const departmentOptions = useMemo<SelectOption[]>(() => departments.map((department) => ({ value: String(department.id), label: getDepartmentLabel(department.code, department.display_name) })), [departments]);
  const fieldClass = (field: FieldName) => `input ${errors[field] ? "border-rose-500 focus:border-rose-500 focus:ring-rose-100" : ""}`;
  const textAreaClass = (field: FieldName) => `textarea ${errors[field] ? "border-rose-500 focus:border-rose-500 focus:ring-rose-100" : ""}`;
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const nextErrors = validate(values); setErrors(nextErrors); if (Object.keys(nextErrors).length) return; const payload: EmployeePayload = { ...values, teaching_experience: Number(values.teaching_experience), grade_post: Number(values.grade_post), step: Number(values.step), notes: (values.notes ?? "").trim() || null }; setIsSubmitting(true); setSubmitError(""); try { if (employee) { await updateEmployee(employee.id, payload); onSaved("اطلاعات کارمند به‌روزرسانی شد."); } else { await createEmployee(payload); onSaved("کارمند جدید با موفقیت ثبت شد."); } onOpenChange(false); } catch { setSubmitError("ثبت اطلاعات با مشکل روبه‌رو شد. لطفاً داده‌ها را بررسی کرده و دوباره تلاش کنید."); } finally { setIsSubmitting(false); } };
  const title = employee ? "ویرایش کارمند" : "افزودن کارمند";
  const submitLabel = employee ? "ذخیره تغییرات" : "ثبت اطلاعات";
  return <AppDialog open={open} onOpenChange={onOpenChange} size="xl" title={title} description="اطلاعات کارمند را تکمیل کنید." footer={<><Button disabled={isSubmitting} variant="secondary" onClick={() => onOpenChange(false)}>انصراف</Button><Button form="employee-form" type="submit" disabled={isSubmitting} variant="primary">{isSubmitting ? <><LoaderCircle className="animate-spin" size={16} />در حال ثبت</> : submitLabel}</Button></>}>
    <form id="employee-form" noValidate onSubmit={submit}>
      {submitError ? <div role="alert" className="mb-4 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-800">{submitError}</div> : null}
      <FormSection title="مشخصات فردی"><div className="grid gap-4 sm:grid-cols-2"><Field label="اسم" field="name" errors={errors}><input className={fieldClass("name")} value={values.name} onChange={(event) => setValue("name", event.target.value)} /></Field><Field label="ولد" field="father_name" errors={errors}><input className={fieldClass("father_name")} value={values.father_name} onChange={(event) => setValue("father_name", event.target.value)} /></Field><Field label="ولدیت" field="grandfather_name" errors={errors}><input className={fieldClass("grandfather_name")} value={values.grandfather_name} onChange={(event) => setValue("grandfather_name", event.target.value)} /></Field><Field label="شماره تماس" field="phone_number" errors={errors}><input dir="ltr" className={fieldClass("phone_number")} value={values.phone_number} onChange={(event) => setValue("phone_number", event.target.value)} /></Field></div></FormSection>
      <FormSection title="اطلاعات وظیفوی"><div className="grid gap-4 sm:grid-cols-2"><Field label="مکتب / محل وظیفه" field="school_workplace" errors={errors}><input className={fieldClass("school_workplace")} value={values.school_workplace} onChange={(event) => setValue("school_workplace", event.target.value)} /></Field><Field label="شهر / ولسوالی" field="city_district" errors={errors}><input className={fieldClass("city_district")} value={values.city_district} onChange={(event) => setValue("city_district", event.target.value)} /></Field><Field label="عنوان وظیفه" field="job_title_code" errors={errors}><SearchableSelect value={values.job_title_code} onChange={(value) => setValue("job_title_code", value)} placeholder="انتخاب عنوان وظیفه" options={Object.entries(jobTitleLabels).map(([value, label]) => ({ value, label }))} /></Field><Field className="sm:col-span-2" label="دیپارتمنت مربوطه" field="department_ids" errors={errors}><MultiSelect values={values.department_ids.map(String)} onChange={(selected) => setValue("department_ids", selected.map(Number))} placeholder="انتخاب دیپارتمنت" options={departmentOptions} /></Field></div><p className="mt-2 text-xs leading-5 text-muted">برای عنوان‌های غیرمعلم، دیپارتمنت تعلیم و تربیه توسط سیستم اضافه و حفظ می‌شود.</p></FormSection>
      <FormSection title="اطلاعات تحصیلی"><div className="grid gap-4 sm:grid-cols-2"><Field label="رشته تحصیلی" field="field_of_study" errors={errors}><input className={fieldClass("field_of_study")} value={values.field_of_study} onChange={(event) => setValue("field_of_study", event.target.value)} /></Field><Field label="درجه تحصیل" field="education_level" errors={errors}><SearchableSelect value={values.education_level} onChange={(value) => setValue("education_level", value)} placeholder="انتخاب درجه تحصیل" options={educationLevelOptions.map((value) => ({ value, label: value }))} /></Field></div></FormSection>
      <FormSection title="اطلاعات مسلکی"><div className="grid gap-4 sm:grid-cols-3"><Field className="sm:col-span-3" label="مضامین که تدریس می‌کند" field="subjects_taught" errors={errors}><textarea className={textAreaClass("subjects_taught")} value={values.subjects_taught} onChange={(event) => setValue("subjects_taught", event.target.value)} /></Field><Field label="سابقه تدریس" field="teaching_experience" errors={errors}><input type="number" min="0" className={fieldClass("teaching_experience")} value={values.teaching_experience} onChange={(event) => setValue("teaching_experience", event.target.value)} /></Field><Field label="بست" field="grade_post" errors={errors}><input type="number" min="0" className={fieldClass("grade_post")} value={values.grade_post} onChange={(event) => setValue("grade_post", event.target.value)} /></Field><Field label="قدم" field="step" errors={errors}><input type="number" min="0" className={fieldClass("step")} value={values.step} onChange={(event) => setValue("step", event.target.value)} /></Field><Field label="ارزیابی موفق" field="successful_evaluation" errors={errors}><input className={fieldClass("successful_evaluation")} value={values.successful_evaluation} onChange={(event) => setValue("successful_evaluation", event.target.value)} /></Field><Field label="مطابق رشته" field="field_match_code" errors={errors}><SearchableSelect value={values.field_match_code} onChange={(value) => setValue("field_match_code", value)} placeholder="انتخاب وضعیت رشته" options={Object.entries(fieldMatchLabels).map(([value, label]) => ({ value, label }))} /></Field></div></FormSection>
      <FormSection title="ملاحظات"><Field label="ملاحظات" field="notes" errors={errors}><textarea className={textAreaClass("notes")} value={values.notes ?? ""} onChange={(event) => setValue("notes", event.target.value)} /></Field></FormSection>
    </form>
  </AppDialog>;
}
function FormSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-6 border-t border-line pt-5 first:mt-0 first:border-t-0 first:pt-0"><h2 className="mb-3 text-sm font-semibold text-ink">{title}</h2>{children}</section>; }
function Field({ label, field, errors, children, className = "" }: { label: string; field: FieldName; errors: FieldErrors; children: React.ReactNode; className?: string }) { return <label className={`block ${className}`}><span className="mb-1.5 block text-sm font-medium text-ink">{label}</span>{children}{errors[field] ? <p className="mt-1 text-xs text-rose-700">{errors[field]}</p> : null}</label>; }
